/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Demux4
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel,
    input in
);
    assign out_0 = (sel == 4'h0)? in : Default;
    assign out_1 = (sel == 4'h1)? in : Default;
    assign out_2 = (sel == 4'h2)? in : Default;
    assign out_3 = (sel == 4'h3)? in : Default;
    assign out_4 = (sel == 4'h4)? in : Default;
    assign out_5 = (sel == 4'h5)? in : Default;
    assign out_6 = (sel == 4'h6)? in : Default;
    assign out_7 = (sel == 4'h7)? in : Default;
    assign out_8 = (sel == 4'h8)? in : Default;
    assign out_9 = (sel == 4'h9)? in : Default;
    assign out_10 = (sel == 4'ha)? in : Default;
    assign out_11 = (sel == 4'hb)? in : Default;
    assign out_12 = (sel == 4'hc)? in : Default;
    assign out_13 = (sel == 4'hd)? in : Default;
    assign out_14 = (sel == 4'he)? in : Default;
    assign out_15 = (sel == 4'hf)? in : Default;
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_8x1
(
    input [2:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    output reg out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Demux3
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    input [2:0] sel,
    input in
);
    assign out_0 = (sel == 3'h0)? in : Default;
    assign out_1 = (sel == 3'h1)? in : Default;
    assign out_2 = (sel == 3'h2)? in : Default;
    assign out_3 = (sel == 3'h3)? in : Default;
    assign out_4 = (sel == 3'h4)? in : Default;
    assign out_5 = (sel == 3'h5)? in : Default;
    assign out_6 = (sel == 3'h6)? in : Default;
    assign out_7 = (sel == 3'h7)? in : Default;
endmodule

module DIG_ROM_512X5_FilterKernel (
    input [8:0] A,
    input sel,
    output reg [4:0] D
);
    reg [4:0] my_rom [0:511];

    always @ (*) begin
        if (~sel)
            D = 5'hz;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 5'h0;
        my_rom[1] = 5'h1;
        my_rom[2] = 5'h2;
        my_rom[3] = 5'h3;
        my_rom[4] = 5'h1;
        my_rom[5] = 5'h2;
        my_rom[6] = 5'h3;
        my_rom[7] = 5'h4;
        my_rom[8] = 5'h2;
        my_rom[9] = 5'h3;
        my_rom[10] = 5'h4;
        my_rom[11] = 5'h5;
        my_rom[12] = 5'h3;
        my_rom[13] = 5'h4;
        my_rom[14] = 5'h5;
        my_rom[15] = 5'h6;
        my_rom[16] = 5'h4;
        my_rom[17] = 5'h5;
        my_rom[18] = 5'h6;
        my_rom[19] = 5'h7;
        my_rom[20] = 5'h5;
        my_rom[21] = 5'h6;
        my_rom[22] = 5'h7;
        my_rom[23] = 5'h8;
        my_rom[24] = 5'h6;
        my_rom[25] = 5'h7;
        my_rom[26] = 5'h8;
        my_rom[27] = 5'h9;
        my_rom[28] = 5'h7;
        my_rom[29] = 5'h8;
        my_rom[30] = 5'h9;
        my_rom[31] = 5'ha;
        my_rom[32] = 5'h2;
        my_rom[33] = 5'h3;
        my_rom[34] = 5'h4;
        my_rom[35] = 5'h5;
        my_rom[36] = 5'h3;
        my_rom[37] = 5'h4;
        my_rom[38] = 5'h5;
        my_rom[39] = 5'h6;
        my_rom[40] = 5'h4;
        my_rom[41] = 5'h5;
        my_rom[42] = 5'h6;
        my_rom[43] = 5'h7;
        my_rom[44] = 5'h5;
        my_rom[45] = 5'h6;
        my_rom[46] = 5'h7;
        my_rom[47] = 5'h8;
        my_rom[48] = 5'h6;
        my_rom[49] = 5'h7;
        my_rom[50] = 5'h8;
        my_rom[51] = 5'h9;
        my_rom[52] = 5'h7;
        my_rom[53] = 5'h8;
        my_rom[54] = 5'h9;
        my_rom[55] = 5'ha;
        my_rom[56] = 5'h8;
        my_rom[57] = 5'h9;
        my_rom[58] = 5'ha;
        my_rom[59] = 5'hb;
        my_rom[60] = 5'h9;
        my_rom[61] = 5'ha;
        my_rom[62] = 5'hb;
        my_rom[63] = 5'hc;
        my_rom[64] = 5'h1;
        my_rom[65] = 5'h2;
        my_rom[66] = 5'h3;
        my_rom[67] = 5'h4;
        my_rom[68] = 5'h2;
        my_rom[69] = 5'h3;
        my_rom[70] = 5'h4;
        my_rom[71] = 5'h5;
        my_rom[72] = 5'h3;
        my_rom[73] = 5'h4;
        my_rom[74] = 5'h5;
        my_rom[75] = 5'h6;
        my_rom[76] = 5'h4;
        my_rom[77] = 5'h5;
        my_rom[78] = 5'h6;
        my_rom[79] = 5'h7;
        my_rom[80] = 5'h5;
        my_rom[81] = 5'h6;
        my_rom[82] = 5'h7;
        my_rom[83] = 5'h8;
        my_rom[84] = 5'h6;
        my_rom[85] = 5'h7;
        my_rom[86] = 5'h8;
        my_rom[87] = 5'h9;
        my_rom[88] = 5'h7;
        my_rom[89] = 5'h8;
        my_rom[90] = 5'h9;
        my_rom[91] = 5'ha;
        my_rom[92] = 5'h8;
        my_rom[93] = 5'h9;
        my_rom[94] = 5'ha;
        my_rom[95] = 5'hb;
        my_rom[96] = 5'h3;
        my_rom[97] = 5'h4;
        my_rom[98] = 5'h5;
        my_rom[99] = 5'h6;
        my_rom[100] = 5'h4;
        my_rom[101] = 5'h5;
        my_rom[102] = 5'h6;
        my_rom[103] = 5'h7;
        my_rom[104] = 5'h5;
        my_rom[105] = 5'h6;
        my_rom[106] = 5'h7;
        my_rom[107] = 5'h8;
        my_rom[108] = 5'h6;
        my_rom[109] = 5'h7;
        my_rom[110] = 5'h8;
        my_rom[111] = 5'h9;
        my_rom[112] = 5'h7;
        my_rom[113] = 5'h8;
        my_rom[114] = 5'h9;
        my_rom[115] = 5'ha;
        my_rom[116] = 5'h8;
        my_rom[117] = 5'h9;
        my_rom[118] = 5'ha;
        my_rom[119] = 5'hb;
        my_rom[120] = 5'h9;
        my_rom[121] = 5'ha;
        my_rom[122] = 5'hb;
        my_rom[123] = 5'hc;
        my_rom[124] = 5'ha;
        my_rom[125] = 5'hb;
        my_rom[126] = 5'hc;
        my_rom[127] = 5'hd;
        my_rom[128] = 5'h2;
        my_rom[129] = 5'h3;
        my_rom[130] = 5'h4;
        my_rom[131] = 5'h5;
        my_rom[132] = 5'h3;
        my_rom[133] = 5'h4;
        my_rom[134] = 5'h5;
        my_rom[135] = 5'h6;
        my_rom[136] = 5'h4;
        my_rom[137] = 5'h5;
        my_rom[138] = 5'h6;
        my_rom[139] = 5'h7;
        my_rom[140] = 5'h5;
        my_rom[141] = 5'h6;
        my_rom[142] = 5'h7;
        my_rom[143] = 5'h8;
        my_rom[144] = 5'h6;
        my_rom[145] = 5'h7;
        my_rom[146] = 5'h8;
        my_rom[147] = 5'h9;
        my_rom[148] = 5'h7;
        my_rom[149] = 5'h8;
        my_rom[150] = 5'h9;
        my_rom[151] = 5'ha;
        my_rom[152] = 5'h8;
        my_rom[153] = 5'h9;
        my_rom[154] = 5'ha;
        my_rom[155] = 5'hb;
        my_rom[156] = 5'h9;
        my_rom[157] = 5'ha;
        my_rom[158] = 5'hb;
        my_rom[159] = 5'hc;
        my_rom[160] = 5'h4;
        my_rom[161] = 5'h5;
        my_rom[162] = 5'h6;
        my_rom[163] = 5'h7;
        my_rom[164] = 5'h5;
        my_rom[165] = 5'h6;
        my_rom[166] = 5'h7;
        my_rom[167] = 5'h8;
        my_rom[168] = 5'h6;
        my_rom[169] = 5'h7;
        my_rom[170] = 5'h8;
        my_rom[171] = 5'h9;
        my_rom[172] = 5'h7;
        my_rom[173] = 5'h8;
        my_rom[174] = 5'h9;
        my_rom[175] = 5'ha;
        my_rom[176] = 5'h8;
        my_rom[177] = 5'h9;
        my_rom[178] = 5'ha;
        my_rom[179] = 5'hb;
        my_rom[180] = 5'h9;
        my_rom[181] = 5'ha;
        my_rom[182] = 5'hb;
        my_rom[183] = 5'hc;
        my_rom[184] = 5'ha;
        my_rom[185] = 5'hb;
        my_rom[186] = 5'hc;
        my_rom[187] = 5'hd;
        my_rom[188] = 5'hb;
        my_rom[189] = 5'hc;
        my_rom[190] = 5'hd;
        my_rom[191] = 5'he;
        my_rom[192] = 5'h3;
        my_rom[193] = 5'h4;
        my_rom[194] = 5'h5;
        my_rom[195] = 5'h6;
        my_rom[196] = 5'h4;
        my_rom[197] = 5'h5;
        my_rom[198] = 5'h6;
        my_rom[199] = 5'h7;
        my_rom[200] = 5'h5;
        my_rom[201] = 5'h6;
        my_rom[202] = 5'h7;
        my_rom[203] = 5'h8;
        my_rom[204] = 5'h6;
        my_rom[205] = 5'h7;
        my_rom[206] = 5'h8;
        my_rom[207] = 5'h9;
        my_rom[208] = 5'h7;
        my_rom[209] = 5'h8;
        my_rom[210] = 5'h9;
        my_rom[211] = 5'ha;
        my_rom[212] = 5'h8;
        my_rom[213] = 5'h9;
        my_rom[214] = 5'ha;
        my_rom[215] = 5'hb;
        my_rom[216] = 5'h9;
        my_rom[217] = 5'ha;
        my_rom[218] = 5'hb;
        my_rom[219] = 5'hc;
        my_rom[220] = 5'ha;
        my_rom[221] = 5'hb;
        my_rom[222] = 5'hc;
        my_rom[223] = 5'hd;
        my_rom[224] = 5'h5;
        my_rom[225] = 5'h6;
        my_rom[226] = 5'h7;
        my_rom[227] = 5'h8;
        my_rom[228] = 5'h6;
        my_rom[229] = 5'h7;
        my_rom[230] = 5'h8;
        my_rom[231] = 5'h9;
        my_rom[232] = 5'h7;
        my_rom[233] = 5'h8;
        my_rom[234] = 5'h9;
        my_rom[235] = 5'ha;
        my_rom[236] = 5'h8;
        my_rom[237] = 5'h9;
        my_rom[238] = 5'ha;
        my_rom[239] = 5'hb;
        my_rom[240] = 5'h9;
        my_rom[241] = 5'ha;
        my_rom[242] = 5'hb;
        my_rom[243] = 5'hc;
        my_rom[244] = 5'ha;
        my_rom[245] = 5'hb;
        my_rom[246] = 5'hc;
        my_rom[247] = 5'hd;
        my_rom[248] = 5'hb;
        my_rom[249] = 5'hc;
        my_rom[250] = 5'hd;
        my_rom[251] = 5'he;
        my_rom[252] = 5'hc;
        my_rom[253] = 5'hd;
        my_rom[254] = 5'he;
        my_rom[255] = 5'hf;
        my_rom[256] = 5'h1;
        my_rom[257] = 5'h2;
        my_rom[258] = 5'h3;
        my_rom[259] = 5'h4;
        my_rom[260] = 5'h2;
        my_rom[261] = 5'h3;
        my_rom[262] = 5'h4;
        my_rom[263] = 5'h5;
        my_rom[264] = 5'h3;
        my_rom[265] = 5'h4;
        my_rom[266] = 5'h5;
        my_rom[267] = 5'h6;
        my_rom[268] = 5'h4;
        my_rom[269] = 5'h5;
        my_rom[270] = 5'h6;
        my_rom[271] = 5'h7;
        my_rom[272] = 5'h5;
        my_rom[273] = 5'h6;
        my_rom[274] = 5'h7;
        my_rom[275] = 5'h8;
        my_rom[276] = 5'h6;
        my_rom[277] = 5'h7;
        my_rom[278] = 5'h8;
        my_rom[279] = 5'h9;
        my_rom[280] = 5'h7;
        my_rom[281] = 5'h8;
        my_rom[282] = 5'h9;
        my_rom[283] = 5'ha;
        my_rom[284] = 5'h8;
        my_rom[285] = 5'h9;
        my_rom[286] = 5'ha;
        my_rom[287] = 5'hb;
        my_rom[288] = 5'h3;
        my_rom[289] = 5'h4;
        my_rom[290] = 5'h5;
        my_rom[291] = 5'h6;
        my_rom[292] = 5'h4;
        my_rom[293] = 5'h5;
        my_rom[294] = 5'h6;
        my_rom[295] = 5'h7;
        my_rom[296] = 5'h5;
        my_rom[297] = 5'h6;
        my_rom[298] = 5'h7;
        my_rom[299] = 5'h8;
        my_rom[300] = 5'h6;
        my_rom[301] = 5'h7;
        my_rom[302] = 5'h8;
        my_rom[303] = 5'h9;
        my_rom[304] = 5'h7;
        my_rom[305] = 5'h8;
        my_rom[306] = 5'h9;
        my_rom[307] = 5'ha;
        my_rom[308] = 5'h8;
        my_rom[309] = 5'h9;
        my_rom[310] = 5'ha;
        my_rom[311] = 5'hb;
        my_rom[312] = 5'h9;
        my_rom[313] = 5'ha;
        my_rom[314] = 5'hb;
        my_rom[315] = 5'hc;
        my_rom[316] = 5'ha;
        my_rom[317] = 5'hb;
        my_rom[318] = 5'hc;
        my_rom[319] = 5'hd;
        my_rom[320] = 5'h2;
        my_rom[321] = 5'h3;
        my_rom[322] = 5'h4;
        my_rom[323] = 5'h5;
        my_rom[324] = 5'h3;
        my_rom[325] = 5'h4;
        my_rom[326] = 5'h5;
        my_rom[327] = 5'h6;
        my_rom[328] = 5'h4;
        my_rom[329] = 5'h5;
        my_rom[330] = 5'h6;
        my_rom[331] = 5'h7;
        my_rom[332] = 5'h5;
        my_rom[333] = 5'h6;
        my_rom[334] = 5'h7;
        my_rom[335] = 5'h8;
        my_rom[336] = 5'h6;
        my_rom[337] = 5'h7;
        my_rom[338] = 5'h8;
        my_rom[339] = 5'h9;
        my_rom[340] = 5'h7;
        my_rom[341] = 5'h8;
        my_rom[342] = 5'h9;
        my_rom[343] = 5'ha;
        my_rom[344] = 5'h8;
        my_rom[345] = 5'h9;
        my_rom[346] = 5'ha;
        my_rom[347] = 5'hb;
        my_rom[348] = 5'h9;
        my_rom[349] = 5'ha;
        my_rom[350] = 5'hb;
        my_rom[351] = 5'hc;
        my_rom[352] = 5'h4;
        my_rom[353] = 5'h5;
        my_rom[354] = 5'h6;
        my_rom[355] = 5'h7;
        my_rom[356] = 5'h5;
        my_rom[357] = 5'h6;
        my_rom[358] = 5'h7;
        my_rom[359] = 5'h8;
        my_rom[360] = 5'h6;
        my_rom[361] = 5'h7;
        my_rom[362] = 5'h8;
        my_rom[363] = 5'h9;
        my_rom[364] = 5'h7;
        my_rom[365] = 5'h8;
        my_rom[366] = 5'h9;
        my_rom[367] = 5'ha;
        my_rom[368] = 5'h8;
        my_rom[369] = 5'h9;
        my_rom[370] = 5'ha;
        my_rom[371] = 5'hb;
        my_rom[372] = 5'h9;
        my_rom[373] = 5'ha;
        my_rom[374] = 5'hb;
        my_rom[375] = 5'hc;
        my_rom[376] = 5'ha;
        my_rom[377] = 5'hb;
        my_rom[378] = 5'hc;
        my_rom[379] = 5'hd;
        my_rom[380] = 5'hb;
        my_rom[381] = 5'hc;
        my_rom[382] = 5'hd;
        my_rom[383] = 5'he;
        my_rom[384] = 5'h3;
        my_rom[385] = 5'h4;
        my_rom[386] = 5'h5;
        my_rom[387] = 5'h6;
        my_rom[388] = 5'h4;
        my_rom[389] = 5'h5;
        my_rom[390] = 5'h6;
        my_rom[391] = 5'h7;
        my_rom[392] = 5'h5;
        my_rom[393] = 5'h6;
        my_rom[394] = 5'h7;
        my_rom[395] = 5'h8;
        my_rom[396] = 5'h6;
        my_rom[397] = 5'h7;
        my_rom[398] = 5'h8;
        my_rom[399] = 5'h9;
        my_rom[400] = 5'h7;
        my_rom[401] = 5'h8;
        my_rom[402] = 5'h9;
        my_rom[403] = 5'ha;
        my_rom[404] = 5'h8;
        my_rom[405] = 5'h9;
        my_rom[406] = 5'ha;
        my_rom[407] = 5'hb;
        my_rom[408] = 5'h9;
        my_rom[409] = 5'ha;
        my_rom[410] = 5'hb;
        my_rom[411] = 5'hc;
        my_rom[412] = 5'ha;
        my_rom[413] = 5'hb;
        my_rom[414] = 5'hc;
        my_rom[415] = 5'hd;
        my_rom[416] = 5'h5;
        my_rom[417] = 5'h6;
        my_rom[418] = 5'h7;
        my_rom[419] = 5'h8;
        my_rom[420] = 5'h6;
        my_rom[421] = 5'h7;
        my_rom[422] = 5'h8;
        my_rom[423] = 5'h9;
        my_rom[424] = 5'h7;
        my_rom[425] = 5'h8;
        my_rom[426] = 5'h9;
        my_rom[427] = 5'ha;
        my_rom[428] = 5'h8;
        my_rom[429] = 5'h9;
        my_rom[430] = 5'ha;
        my_rom[431] = 5'hb;
        my_rom[432] = 5'h9;
        my_rom[433] = 5'ha;
        my_rom[434] = 5'hb;
        my_rom[435] = 5'hc;
        my_rom[436] = 5'ha;
        my_rom[437] = 5'hb;
        my_rom[438] = 5'hc;
        my_rom[439] = 5'hd;
        my_rom[440] = 5'hb;
        my_rom[441] = 5'hc;
        my_rom[442] = 5'hd;
        my_rom[443] = 5'he;
        my_rom[444] = 5'hc;
        my_rom[445] = 5'hd;
        my_rom[446] = 5'he;
        my_rom[447] = 5'hf;
        my_rom[448] = 5'h4;
        my_rom[449] = 5'h5;
        my_rom[450] = 5'h6;
        my_rom[451] = 5'h7;
        my_rom[452] = 5'h5;
        my_rom[453] = 5'h6;
        my_rom[454] = 5'h7;
        my_rom[455] = 5'h8;
        my_rom[456] = 5'h6;
        my_rom[457] = 5'h7;
        my_rom[458] = 5'h8;
        my_rom[459] = 5'h9;
        my_rom[460] = 5'h7;
        my_rom[461] = 5'h8;
        my_rom[462] = 5'h9;
        my_rom[463] = 5'ha;
        my_rom[464] = 5'h8;
        my_rom[465] = 5'h9;
        my_rom[466] = 5'ha;
        my_rom[467] = 5'hb;
        my_rom[468] = 5'h9;
        my_rom[469] = 5'ha;
        my_rom[470] = 5'hb;
        my_rom[471] = 5'hc;
        my_rom[472] = 5'ha;
        my_rom[473] = 5'hb;
        my_rom[474] = 5'hc;
        my_rom[475] = 5'hd;
        my_rom[476] = 5'hb;
        my_rom[477] = 5'hc;
        my_rom[478] = 5'hd;
        my_rom[479] = 5'he;
        my_rom[480] = 5'h6;
        my_rom[481] = 5'h7;
        my_rom[482] = 5'h8;
        my_rom[483] = 5'h9;
        my_rom[484] = 5'h7;
        my_rom[485] = 5'h8;
        my_rom[486] = 5'h9;
        my_rom[487] = 5'ha;
        my_rom[488] = 5'h8;
        my_rom[489] = 5'h9;
        my_rom[490] = 5'ha;
        my_rom[491] = 5'hb;
        my_rom[492] = 5'h9;
        my_rom[493] = 5'ha;
        my_rom[494] = 5'hb;
        my_rom[495] = 5'hc;
        my_rom[496] = 5'ha;
        my_rom[497] = 5'hb;
        my_rom[498] = 5'hc;
        my_rom[499] = 5'hd;
        my_rom[500] = 5'hb;
        my_rom[501] = 5'hc;
        my_rom[502] = 5'hd;
        my_rom[503] = 5'he;
        my_rom[504] = 5'hc;
        my_rom[505] = 5'hd;
        my_rom[506] = 5'he;
        my_rom[507] = 5'hf;
        my_rom[508] = 5'hd;
        my_rom[509] = 5'he;
        my_rom[510] = 5'hf;
        my_rom[511] = 5'h10;
    end
endmodule


module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module DemuxBus3
#(
    parameter Bits = 2,
    parameter Default = 0 
)
(
    output [(Bits-1):0] out_0,
    output [(Bits-1):0] out_1,
    output [(Bits-1):0] out_2,
    output [(Bits-1):0] out_3,
    output [(Bits-1):0] out_4,
    output [(Bits-1):0] out_5,
    output [(Bits-1):0] out_6,
    output [(Bits-1):0] out_7,
    input [2:0] sel,
    input [(Bits-1):0] in
);
    assign out_0 = (sel == 3'h0)? in : Default;
    assign out_1 = (sel == 3'h1)? in : Default;
    assign out_2 = (sel == 3'h2)? in : Default;
    assign out_3 = (sel == 3'h3)? in : Default;
    assign out_4 = (sel == 3'h4)? in : Default;
    assign out_5 = (sel == 3'h5)? in : Default;
    assign out_6 = (sel == 3'h6)? in : Default;
    assign out_7 = (sel == 3'h7)? in : Default;
endmodule


module RomInterpretation (
  input [7:0] w3,
  input [7:0] w4,
  input [7:0] w5,
  input [7:0] w6,
  input [7:0] w7,
  input [7:0] w8,
  input [7:0] w9,
  input [7:0] w1,
  input [7:0] w2,
  input clk,
  input en,
  input rst, // active_high
  output [4:0] o1,
  output [4:0] o2,
  output [4:0] o3,
  output [4:0] o4,
  output [4:0] o5,
  output [4:0] o6,
  output [4:0] o7,
  output [4:0] o8
);
  wire [8:0] s0;
  wire [4:0] s1;
  wire [4:0] s2;
  wire s3;
  wire [4:0] s4;
  wire s5;
  wire [4:0] s6;
  wire s7;
  wire [4:0] s8;
  wire s9;
  wire [4:0] s10;
  wire s11;
  wire [4:0] s12;
  wire s13;
  wire [4:0] s14;
  wire s15;
  wire [4:0] s16;
  wire s17;
  wire [2:0] s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire [4:0] s100;
  wire [4:0] s101;
  wire [4:0] s102;
  wire [4:0] s103;
  wire [4:0] s104;
  wire [4:0] s105;
  wire [4:0] s106;
  wire [4:0] s107;
  wire s108;
  wire s109;
  wire s110;
  wire s111;
  wire s112;
  wire s113;
  wire s114;
  wire s115;
  wire s116;
  wire s117;
  wire s118;
  wire tc;
  DIG_Counter_Nbit #(
    .Bits(3)
  )
  DIG_Counter_Nbit_i0 (
    .en( en ),
    .C( clk ),
    .clr( rst ),
    .out( s18 )
  );
  Mux_2x1 Mux_2x1_i1 (
    .sel( rst ),
    .in_0( 1'b1 ),
    .in_1( 1'b0 ),
    .out( s116 )
  );
  assign s19 = w1[0];
  assign s20 = w1[1];
  assign s21 = w1[2];
  assign s22 = w1[3];
  assign s23 = w1[4];
  assign s24 = w1[5];
  assign s25 = w1[6];
  assign s26 = w1[7];
  assign s28 = w2[0];
  assign s29 = w2[1];
  assign s30 = w2[2];
  assign s31 = w2[3];
  assign s32 = w2[4];
  assign s33 = w2[5];
  assign s34 = w2[6];
  assign s35 = w2[7];
  assign s36 = w3[0];
  assign s37 = w3[1];
  assign s38 = w3[2];
  assign s39 = w3[3];
  assign s40 = w3[4];
  assign s41 = w3[5];
  assign s42 = w3[6];
  assign s43 = w3[7];
  assign s44 = w4[0];
  assign s45 = w4[1];
  assign s46 = w4[2];
  assign s47 = w4[3];
  assign s48 = w4[4];
  assign s49 = w4[5];
  assign s50 = w4[6];
  assign s51 = w4[7];
  assign s60 = w5[0];
  assign s61 = w5[1];
  assign s62 = w5[2];
  assign s63 = w5[3];
  assign s64 = w5[4];
  assign s65 = w5[5];
  assign s66 = w5[6];
  assign s67 = w5[7];
  assign s68 = w6[0];
  assign s69 = w6[1];
  assign s70 = w6[2];
  assign s71 = w6[3];
  assign s72 = w6[4];
  assign s73 = w6[5];
  assign s74 = w6[6];
  assign s75 = w6[7];
  assign s76 = w7[0];
  assign s77 = w7[1];
  assign s78 = w7[2];
  assign s79 = w7[3];
  assign s80 = w7[4];
  assign s81 = w7[5];
  assign s82 = w7[6];
  assign s83 = w7[7];
  assign s84 = w8[0];
  assign s85 = w8[1];
  assign s86 = w8[2];
  assign s87 = w8[3];
  assign s88 = w8[4];
  assign s89 = w8[5];
  assign s90 = w8[6];
  assign s91 = w8[7];
  assign s92 = w9[0];
  assign s93 = w9[1];
  assign s94 = w9[2];
  assign s95 = w9[3];
  assign s96 = w9[4];
  assign s97 = w9[5];
  assign s98 = w9[6];
  assign s99 = w9[7];
  Mux_8x1 Mux_8x1_i2 (
    .sel( s18 ),
    .in_0( s19 ),
    .in_1( s20 ),
    .in_2( s21 ),
    .in_3( s22 ),
    .in_4( s23 ),
    .in_5( s24 ),
    .in_6( s25 ),
    .in_7( s26 ),
    .out( s27 )
  );
  Demux3 #(
    .Default(0)
  )
  Demux3_i3 (
    .sel( s18 ),
    .in( 1'b1 ),
    .out_0( s108 ),
    .out_1( s109 ),
    .out_2( s110 ),
    .out_3( s111 ),
    .out_4( s112 ),
    .out_5( s113 ),
    .out_6( s114 ),
    .out_7( s115 )
  );
  Mux_8x1 Mux_8x1_i4 (
    .sel( s18 ),
    .in_0( s28 ),
    .in_1( s29 ),
    .in_2( s30 ),
    .in_3( s31 ),
    .in_4( s32 ),
    .in_5( s33 ),
    .in_6( s34 ),
    .in_7( s35 ),
    .out( s59 )
  );
  Mux_8x1 Mux_8x1_i5 (
    .sel( s18 ),
    .in_0( s36 ),
    .in_1( s37 ),
    .in_2( s38 ),
    .in_3( s39 ),
    .in_4( s40 ),
    .in_5( s41 ),
    .in_6( s42 ),
    .in_7( s43 ),
    .out( s58 )
  );
  Mux_8x1 Mux_8x1_i6 (
    .sel( s18 ),
    .in_0( s44 ),
    .in_1( s45 ),
    .in_2( s46 ),
    .in_3( s47 ),
    .in_4( s48 ),
    .in_5( s49 ),
    .in_6( s50 ),
    .in_7( s51 ),
    .out( s57 )
  );
  Mux_8x1 Mux_8x1_i7 (
    .sel( s18 ),
    .in_0( s60 ),
    .in_1( s61 ),
    .in_2( s62 ),
    .in_3( s63 ),
    .in_4( s64 ),
    .in_5( s65 ),
    .in_6( s66 ),
    .in_7( s67 ),
    .out( s56 )
  );
  Mux_8x1 Mux_8x1_i8 (
    .sel( s18 ),
    .in_0( s68 ),
    .in_1( s69 ),
    .in_2( s70 ),
    .in_3( s71 ),
    .in_4( s72 ),
    .in_5( s73 ),
    .in_6( s74 ),
    .in_7( s75 ),
    .out( s55 )
  );
  Mux_8x1 Mux_8x1_i9 (
    .sel( s18 ),
    .in_0( s76 ),
    .in_1( s77 ),
    .in_2( s78 ),
    .in_3( s79 ),
    .in_4( s80 ),
    .in_5( s81 ),
    .in_6( s82 ),
    .in_7( s83 ),
    .out( s54 )
  );
  Mux_8x1 Mux_8x1_i10 (
    .sel( s18 ),
    .in_0( s84 ),
    .in_1( s85 ),
    .in_2( s86 ),
    .in_3( s87 ),
    .in_4( s88 ),
    .in_5( s89 ),
    .in_6( s90 ),
    .in_7( s91 ),
    .out( s53 )
  );
  Mux_8x1 Mux_8x1_i11 (
    .sel( s18 ),
    .in_0( s92 ),
    .in_1( s93 ),
    .in_2( s94 ),
    .in_3( s95 ),
    .in_4( s96 ),
    .in_5( s97 ),
    .in_6( s98 ),
    .in_7( s99 ),
    .out( s52 )
  );
  assign s0[0] = s52;
  assign s0[1] = s53;
  assign s0[2] = s54;
  assign s0[3] = s55;
  assign s0[4] = s56;
  assign s0[5] = s57;
  assign s0[6] = s58;
  assign s0[7] = s59;
  assign s0[8] = s27;
  assign s117 = (s115 | rst);
  // FilterKernel
  DIG_ROM_512X5_FilterKernel DIG_ROM_512X5_FilterKernel_i12 (
    .A( s0 ),
    .sel( 1'b1 ),
    .D( s1 )
  );
  DIG_Register DIG_Register_i13 (
    .D( s116 ),
    .C( clk ),
    .en( s117 ),
    .Q( s118 )
  );
  DemuxBus3 #(
    .Bits(5),
    .Default(0)
  )
  DemuxBus3_i14 (
    .sel( s18 ),
    .in( s1 ),
    .out_0( s100 ),
    .out_1( s101 ),
    .out_2( s102 ),
    .out_3( s103 ),
    .out_4( s104 ),
    .out_5( s105 ),
    .out_6( s106 ),
    .out_7( s107 )
  );
  assign tc = ~ s118;
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i15 (
    .sel( rst ),
    .in_0( s100 ),
    .in_1( 5'b0 ),
    .out( s2 )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i16 (
    .sel( rst ),
    .in_0( s101 ),
    .in_1( 5'b0 ),
    .out( s4 )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i17 (
    .sel( rst ),
    .in_0( s102 ),
    .in_1( 5'b0 ),
    .out( s6 )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i18 (
    .sel( rst ),
    .in_0( s103 ),
    .in_1( 5'b0 ),
    .out( s8 )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i19 (
    .sel( rst ),
    .in_0( s104 ),
    .in_1( 5'b0 ),
    .out( s10 )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i20 (
    .sel( rst ),
    .in_0( s105 ),
    .in_1( 5'b0 ),
    .out( s12 )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i21 (
    .sel( rst ),
    .in_0( s106 ),
    .in_1( 5'b0 ),
    .out( s14 )
  );
  Mux_2x1_NBits #(
    .Bits(5)
  )
  Mux_2x1_NBits_i22 (
    .sel( rst ),
    .in_0( s107 ),
    .in_1( 5'b0 ),
    .out( s16 )
  );
  assign s3 = ((s108 & tc) | rst);
  assign s5 = ((s109 & tc) | rst);
  assign s7 = ((s110 & tc) | rst);
  assign s9 = ((s111 & tc) | rst);
  assign s11 = ((s112 & tc) | rst);
  assign s13 = ((s113 & tc) | rst);
  assign s15 = ((s114 & tc) | rst);
  assign s17 = ((s115 & tc) | rst);
  // r1
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i23 (
    .D( s2 ),
    .C( clk ),
    .en( s3 ),
    .Q( o1 )
  );
  // r2
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i24 (
    .D( s4 ),
    .C( clk ),
    .en( s5 ),
    .Q( o2 )
  );
  // r3
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i25 (
    .D( s6 ),
    .C( clk ),
    .en( s7 ),
    .Q( o3 )
  );
  // r4
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i26 (
    .D( s8 ),
    .C( clk ),
    .en( s9 ),
    .Q( o4 )
  );
  // r5
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i27 (
    .D( s10 ),
    .C( clk ),
    .en( s11 ),
    .Q( o5 )
  );
  // r6
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i28 (
    .D( s12 ),
    .C( clk ),
    .en( s13 ),
    .Q( o6 )
  );
  // r7
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i29 (
    .D( s14 ),
    .C( clk ),
    .en( s15 ),
    .Q( o7 )
  );
  // r8
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i30 (
    .D( s16 ),
    .C( clk ),
    .en( s17 ),
    .Q( o8 )
  );
endmodule

module \5auf8  (
  input [4:0] in,
  output [7:0] ou5
);
  assign ou5[4:0] = in;
  assign ou5[7:5] = 3'b0;
endmodule

module conv5to8 (
  input [4:0] in,
  output [15:0] \10bdd 
);
  assign \10bdd [0] = in[0];
  assign \10bdd [1] = 1'b1;
  assign \10bdd [2] = in[1];
  assign \10bdd [3] = 1'b1;
  assign \10bdd [4] = in[2];
  assign \10bdd [5] = 1'b1;
  assign \10bdd [6] = in[3];
  assign \10bdd [7] = 1'b1;
  assign \10bdd [8] = in[4];
  assign \10bdd [9] = 1'b1;
  assign \10bdd [10] = 1'b0;
  assign \10bdd [11] = 1'b1;
  assign \10bdd [12] = 1'b0;
  assign \10bdd [13] = 1'b1;
  assign \10bdd [14] = 1'b0;
  assign \10bdd [15] = 1'b1;
endmodule

module shift1 (
  input [7:0] in,
  output [7:0] out
);
  assign out[0] = 1'b0;
  assign out[1] = in[0];
  assign out[2] = in[1];
  assign out[3] = in[2];
  assign out[4] = in[3];
  assign out[5] = in[4];
  assign out[6] = in[5];
  assign out[7] = in[6];
endmodule

module shift2 (
  input [7:0] in,
  output [7:0] out
);
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  assign out[2] = in[0];
  assign out[3] = in[1];
  assign out[4] = in[2];
  assign out[5] = in[3];
  assign out[6] = in[4];
  assign out[7] = in[5];
endmodule

module shift3 (
  input [7:0] in,
  output [7:0] out
);
  wire s0;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  assign out[2] = 1'b0;
  assign out[3] = in[0];
  assign out[4] = in[1];
  assign out[5] = in[2];
  assign out[6] = in[3];
  assign out[7] = in[4];
  assign s0 = in[5];
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module \8bit_BSD_TC_Adder  (
  input [7:0] inTC,
  input [15:0] inBSD,
  output [15:0] bsdOut,
  output [1:0] c
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  assign s17 = inTC[0];
  assign s12 = inTC[1];
  assign s7 = inTC[2];
  assign s2 = inTC[3];
  assign s20 = inTC[4];
  assign s21 = inTC[5];
  assign s22 = inTC[6];
  assign s23 = inTC[7];
  assign s15 = inBSD[0];
  assign s16 = inBSD[1];
  assign s10 = inBSD[2];
  assign s11 = inBSD[3];
  assign s5 = inBSD[4];
  assign s6 = inBSD[5];
  assign s0 = inBSD[6];
  assign s1 = inBSD[7];
  assign s24 = inBSD[8];
  assign s25 = inBSD[9];
  assign s26 = inBSD[10];
  assign s27 = inBSD[11];
  assign s28 = inBSD[12];
  assign s29 = inBSD[13];
  assign s30 = inBSD[14];
  assign s31 = inBSD[15];
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i0 (
    .a( s0 ),
    .b( s1 ),
    .c_i( s2 ),
    .s( s3 ),
    .c_o( s4 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i1 (
    .a( s5 ),
    .b( s6 ),
    .c_i( s7 ),
    .s( s8 ),
    .c_o( s9 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i2 (
    .a( s10 ),
    .b( s11 ),
    .c_i( s12 ),
    .s( s13 ),
    .c_o( s14 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i3 (
    .a( s15 ),
    .b( s16 ),
    .c_i( s17 ),
    .s( s18 ),
    .c_o( s19 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i4 (
    .a( s26 ),
    .b( s27 ),
    .c_i( s21 ),
    .s( s34 ),
    .c_o( s35 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i5 (
    .a( s24 ),
    .b( s25 ),
    .c_i( s20 ),
    .s( s32 ),
    .c_o( s33 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i6 (
    .a( s30 ),
    .b( s31 ),
    .c_i( s23 ),
    .s( s38 ),
    .c_o( s39 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i7 (
    .a( s28 ),
    .b( s29 ),
    .c_i( s22 ),
    .s( s36 ),
    .c_o( s37 )
  );
  assign bsdOut[0] = 1'b0;
  assign bsdOut[1] = s18;
  assign bsdOut[2] = s19;
  assign bsdOut[3] = s13;
  assign bsdOut[4] = s14;
  assign bsdOut[5] = s8;
  assign bsdOut[6] = s9;
  assign bsdOut[7] = s3;
  assign bsdOut[8] = s4;
  assign bsdOut[9] = s32;
  assign bsdOut[10] = s33;
  assign bsdOut[11] = s34;
  assign bsdOut[12] = s35;
  assign bsdOut[13] = s36;
  assign bsdOut[14] = s37;
  assign bsdOut[15] = s38;
  assign c[0] = s39;
  assign c[1] = 1'b1;
endmodule

module \18auf24  (
  input [17:0] in,
  output [25:0] ou5
);
  assign ou5[17:0] = in;
  assign ou5[18] = 1'b0;
  assign ou5[19] = 1'b1;
  assign ou5[20] = 1'b0;
  assign ou5[21] = 1'b1;
  assign ou5[22] = 1'b0;
  assign ou5[23] = 1'b1;
  assign ou5[24] = 1'b0;
  assign ou5[25] = 1'b1;
endmodule

module shift4 (
  input [17:0] in,
  output [25:0] out
);
  assign out[0] = 1'b1;
  assign out[1] = 1'b0;
  assign out[2] = 1'b1;
  assign out[3] = 1'b0;
  assign out[4] = 1'b1;
  assign out[5] = 1'b0;
  assign out[6] = 1'b1;
  assign out[7] = 1'b0;
  assign out[8] = in[0];
  assign out[9] = in[1];
  assign out[10] = in[2];
  assign out[11] = in[3];
  assign out[12] = in[4];
  assign out[13] = in[5];
  assign out[14] = in[6];
  assign out[15] = in[7];
  assign out[16] = in[8];
  assign out[17] = in[9];
  assign out[18] = in[10];
  assign out[19] = in[11];
  assign out[20] = in[12];
  assign out[21] = in[13];
  assign out[22] = in[14];
  assign out[23] = in[15];
  assign out[24] = in[16];
  assign out[25] = in[17];
endmodule

module \13BitBSD  (
  input [25:0] inA,
  input [25:0] inB,
  output [27:0] out
);
  wire \1 ;
  wire \1b ;
  wire \2 ;
  wire s0;
  wire s1;
  wire \2b ;
  wire s2;
  wire s3;
  wire \3 ;
  wire \3b ;
  wire \4 ;
  wire s4;
  wire s5;
  wire \4b ;
  wire s6;
  wire s7;
  wire \5 ;
  wire \5b ;
  wire \6 ;
  wire s8;
  wire s9;
  wire \6b ;
  wire s10;
  wire s11;
  wire \7 ;
  wire \7b ;
  wire \8 ;
  wire s12;
  wire s13;
  wire \8b ;
  wire s14;
  wire s15;
  wire \9 ;
  wire \9b ;
  wire \10 ;
  wire s16;
  wire s17;
  wire \10b ;
  wire s18;
  wire s19;
  wire \11 ;
  wire \11b ;
  wire \12 ;
  wire s20;
  wire s21;
  wire \12b ;
  wire s22;
  wire s23;
  wire \13 ;
  wire \13b ;
  wire \14 ;
  wire s24;
  wire s25;
  wire \14b ;
  wire s26;
  wire s27;
  wire \15 ;
  wire \15b ;
  wire \16 ;
  wire s28;
  wire s29;
  wire \16b ;
  wire s30;
  wire s31;
  wire [15:0] s32;
  wire [15:0] s33;
  wire [15:0] s34;
  wire \1c ;
  wire \1bc ;
  wire \2c ;
  wire s35;
  wire s36;
  wire \2bc ;
  wire s37;
  wire s38;
  wire \3c ;
  wire \3bc ;
  wire \4c ;
  wire s39;
  wire s40;
  wire \4bc ;
  wire s41;
  wire s42;
  wire \5c ;
  wire \5bc ;
  wire \6c ;
  wire s43;
  wire s44;
  wire \6bc ;
  wire s45;
  wire s46;
  wire \7c ;
  wire \7bc ;
  wire \8c ;
  wire s47;
  wire s48;
  wire \8bc ;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire [11:0] s54;
  wire [9:0] s55;
  wire \9c ;
  wire \10c ;
  wire [9:0] s56;
  wire \9bc ;
  wire \10bc ;
  wire s57;
  assign s33 = inA[15:0];
  assign s55 = inA[25:16];
  assign s34 = inB[15:0];
  assign s56 = inB[25:16];
  assign \1  = s33[0];
  assign \2  = s33[1];
  assign \3  = s33[2];
  assign \4  = s33[3];
  assign \5  = s33[4];
  assign \6  = s33[5];
  assign \7  = s33[6];
  assign \8  = s33[7];
  assign \9  = s33[8];
  assign \10  = s33[9];
  assign \11  = s33[10];
  assign \12  = s33[11];
  assign \13  = s33[12];
  assign \14  = s33[13];
  assign \15  = s33[14];
  assign \16  = s33[15];
  assign \1b  = s34[0];
  assign \2b  = s34[1];
  assign \3b  = s34[2];
  assign \4b  = s34[3];
  assign \5b  = s34[4];
  assign \6b  = s34[5];
  assign \7b  = s34[6];
  assign \8b  = s34[7];
  assign \9b  = s34[8];
  assign \10b  = s34[9];
  assign \11b  = s34[10];
  assign \12b  = s34[11];
  assign \13b  = s34[12];
  assign \14b  = s34[13];
  assign \15b  = s34[14];
  assign \16b  = s34[15];
  assign \1c  = s55[0];
  assign \2c  = s55[1];
  assign \3c  = s55[2];
  assign \4c  = s55[3];
  assign \5c  = s55[4];
  assign \6c  = s55[5];
  assign \7c  = s55[6];
  assign \8c  = s55[7];
  assign \9c  = s55[8];
  assign \10c  = s55[9];
  assign \1bc  = s56[0];
  assign \2bc  = s56[1];
  assign \3bc  = s56[2];
  assign \4bc  = s56[3];
  assign \5bc  = s56[4];
  assign \6bc  = s56[5];
  assign \7bc  = s56[6];
  assign \8bc  = s56[7];
  assign \9bc  = s56[8];
  assign \10bc  = s56[9];
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i0 (
    .a( \1  ),
    .b( \1b  ),
    .c_i( \2  ),
    .s( s0 ),
    .c_o( s1 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i1 (
    .a( \3  ),
    .b( \3b  ),
    .c_i( \4  ),
    .s( s4 ),
    .c_o( s5 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i2 (
    .a( \5  ),
    .b( \5b  ),
    .c_i( \6  ),
    .s( s8 ),
    .c_o( s9 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i3 (
    .a( \7  ),
    .b( \7b  ),
    .c_i( \8  ),
    .s( s12 ),
    .c_o( s13 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i4 (
    .a( \9  ),
    .b( \9b  ),
    .c_i( \10  ),
    .s( s16 ),
    .c_o( s17 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i5 (
    .a( \11  ),
    .b( \11b  ),
    .c_i( \12  ),
    .s( s20 ),
    .c_o( s21 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i6 (
    .a( \13  ),
    .b( \13b  ),
    .c_i( \14  ),
    .s( s24 ),
    .c_o( s25 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i7 (
    .a( \15  ),
    .b( \15b  ),
    .c_i( \16  ),
    .s( s28 ),
    .c_o( s29 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i8 (
    .a( \1c  ),
    .b( \1bc  ),
    .c_i( \2c  ),
    .s( s35 ),
    .c_o( s36 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i9 (
    .a( \3c  ),
    .b( \3bc  ),
    .c_i( \4c  ),
    .s( s39 ),
    .c_o( s40 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i10 (
    .a( \5c  ),
    .b( \5bc  ),
    .c_i( \6c  ),
    .s( s43 ),
    .c_o( s44 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i11 (
    .a( \7c  ),
    .b( \7bc  ),
    .c_i( \8c  ),
    .s( s47 ),
    .c_o( s48 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i12 (
    .a( \9c  ),
    .b( \9bc  ),
    .c_i( \10c  ),
    .s( s57 ),
    .c_o( s53 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i13 (
    .a( 1'b1 ),
    .b( s0 ),
    .c_i( \2b  ),
    .s( s2 ),
    .c_o( s3 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i14 (
    .a( s1 ),
    .b( s4 ),
    .c_i( \4b  ),
    .s( s6 ),
    .c_o( s7 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i15 (
    .a( s5 ),
    .b( s8 ),
    .c_i( \6b  ),
    .s( s10 ),
    .c_o( s11 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i16 (
    .a( s9 ),
    .b( s12 ),
    .c_i( \8b  ),
    .s( s14 ),
    .c_o( s15 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i17 (
    .a( s13 ),
    .b( s16 ),
    .c_i( \10b  ),
    .s( s18 ),
    .c_o( s19 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i18 (
    .a( s17 ),
    .b( s20 ),
    .c_i( \12b  ),
    .s( s22 ),
    .c_o( s23 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i19 (
    .a( s21 ),
    .b( s24 ),
    .c_i( \14b  ),
    .s( s26 ),
    .c_o( s27 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i20 (
    .a( s25 ),
    .b( s28 ),
    .c_i( \16b  ),
    .s( s30 ),
    .c_o( s31 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i21 (
    .a( s29 ),
    .b( s35 ),
    .c_i( \2bc  ),
    .s( s37 ),
    .c_o( s38 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i22 (
    .a( s36 ),
    .b( s39 ),
    .c_i( \4bc  ),
    .s( s41 ),
    .c_o( s42 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i23 (
    .a( s40 ),
    .b( s43 ),
    .c_i( \6bc  ),
    .s( s45 ),
    .c_o( s46 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i24 (
    .a( s44 ),
    .b( s47 ),
    .c_i( \8bc  ),
    .s( s49 ),
    .c_o( s50 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i25 (
    .a( s48 ),
    .b( s57 ),
    .c_i( \10bc  ),
    .s( s51 ),
    .c_o( s52 )
  );
  assign s32[0] = 1'b0;
  assign s32[1] = s2;
  assign s32[2] = s3;
  assign s32[3] = s6;
  assign s32[4] = s7;
  assign s32[5] = s10;
  assign s32[6] = s11;
  assign s32[7] = s14;
  assign s32[8] = s15;
  assign s32[9] = s18;
  assign s32[10] = s19;
  assign s32[11] = s22;
  assign s32[12] = s23;
  assign s32[13] = s26;
  assign s32[14] = s27;
  assign s32[15] = s30;
  assign s54[0] = s31;
  assign s54[1] = s37;
  assign s54[2] = s38;
  assign s54[3] = s41;
  assign s54[4] = s42;
  assign s54[5] = s45;
  assign s54[6] = s46;
  assign s54[7] = s49;
  assign s54[8] = s50;
  assign s54[9] = s51;
  assign s54[10] = s52;
  assign s54[11] = s53;
  assign out[15:0] = s32;
  assign out[27:16] = s54;
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module TinyTapeoutAdderTree2 (
  input [7:0] ui_in,
  input clk,
  input [7:0] uio_in, // 0,1,2,3 => reg mux
                      // 4,5 => sel out
                      // 6,7 => en, write
  input rst,
  output [7:0] uo_out
);
  wire [4:0] s0;
  wire [7:0] s1;
  wire [4:0] s2;
  wire [7:0] s3;
  wire [4:0] s4;
  wire [7:0] s5;
  wire [7:0] s6;
  wire [7:0] s7;
  wire [7:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [1:0] s13;
  wire [17:0] s14;
  wire [25:0] s15;
  wire [17:0] s16;
  wire [25:0] s17;
  wire [27:0] s18;
  wire [4:0] s19;
  wire [7:0] s20;
  wire [4:0] s21;
  wire [7:0] s22;
  wire [4:0] s23;
  wire [7:0] s24;
  wire [7:0] s25;
  wire [7:0] s26;
  wire [7:0] s27;
  wire [15:0] s28;
  wire [15:0] s29;
  wire [15:0] s30;
  wire [15:0] s31;
  wire [1:0] s32;
  wire [4:0] s33;
  wire [4:0] s34;
  wire [7:0] s35;
  wire s36;
  wire [7:0] t2;
  wire s37;
  wire [7:0] t3;
  wire s38;
  wire [7:0] t4;
  wire s39;
  wire [7:0] t5;
  wire s40;
  wire [7:0] t6;
  wire s41;
  wire [7:0] t7;
  wire s42;
  wire [7:0] t8;
  wire [3:0] s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire [7:0] t1;
  wire [1:0] s54;
  wire [1:0] s55;
  wire [7:0] s56;
  wire [7:0] s57;
  wire [7:0] s58;
  wire [7:0] s59;
  wire write;
  wire en;
  wire [7:0] t9;
  wire s60;
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i0 (
    .sel( rst ),
    .in_0( ui_in ),
    .in_1( 8'b0 ),
    .out( s35 )
  );
  assign s43 = uio_in[3:0];
  assign s54 = uio_in[5:4];
  assign s55 = uio_in[7:6];
  Demux4 #(
    .Default(0)
  )
  Demux4_i1 (
    .sel( s43 ),
    .in( 1'b1 ),
    .out_0( s44 ),
    .out_1( s45 ),
    .out_2( s46 ),
    .out_3( s47 ),
    .out_4( s48 ),
    .out_5( s49 ),
    .out_6( s50 ),
    .out_7( s51 ),
    .out_8( s52 )
  );
  assign en = s55[0];
  assign write = s55[1];
  assign s53 = ((s44 & write) | rst);
  assign s36 = ((s45 & write) | rst);
  assign s37 = ((s46 & write) | rst);
  assign s38 = ((s47 & write) | rst);
  assign s39 = ((s48 & write) | rst);
  assign s40 = ((s49 & write) | rst);
  assign s41 = ((s50 & write) | rst);
  assign s42 = ((s51 & write) | rst);
  assign s60 = ((s52 & write) | rst);
  // R1
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i2 (
    .D( s35 ),
    .C( clk ),
    .en( s36 ),
    .Q( t2 )
  );
  // R2
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i3 (
    .D( s35 ),
    .C( clk ),
    .en( s37 ),
    .Q( t3 )
  );
  // R3
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i4 (
    .D( s35 ),
    .C( clk ),
    .en( s38 ),
    .Q( t4 )
  );
  // R4
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i5 (
    .D( s35 ),
    .C( clk ),
    .en( s39 ),
    .Q( t5 )
  );
  // R5
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i6 (
    .D( s35 ),
    .C( clk ),
    .en( s40 ),
    .Q( t6 )
  );
  // R6
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i7 (
    .D( s35 ),
    .C( clk ),
    .en( s41 ),
    .Q( t7 )
  );
  // R7
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i8 (
    .D( s35 ),
    .C( clk ),
    .en( s42 ),
    .Q( t8 )
  );
  // R0
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i9 (
    .D( s35 ),
    .C( clk ),
    .en( s53 ),
    .Q( t1 )
  );
  // R8
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i10 (
    .D( s35 ),
    .C( clk ),
    .en( s60 ),
    .Q( t9 )
  );
  RomInterpretation RomInterpretation_i11 (
    .w3( t3 ),
    .w4( t4 ),
    .w5( t5 ),
    .w6( t6 ),
    .w7( t7 ),
    .w8( t8 ),
    .w9( t9 ),
    .w1( t1 ),
    .w2( t2 ),
    .clk( clk ),
    .en( en ),
    .rst( rst ),
    .o1( s33 ),
    .o2( s0 ),
    .o3( s2 ),
    .o4( s4 ),
    .o5( s34 ),
    .o6( s19 ),
    .o7( s21 ),
    .o8( s23 )
  );
  \5auf8  \5auf8_i12 (
    .in( s0 ),
    .ou5( s1 )
  );
  \5auf8  \5auf8_i13 (
    .in( s2 ),
    .ou5( s3 )
  );
  \5auf8  \5auf8_i14 (
    .in( s4 ),
    .ou5( s5 )
  );
  \5auf8  \5auf8_i15 (
    .in( s19 ),
    .ou5( s20 )
  );
  \5auf8  \5auf8_i16 (
    .in( s21 ),
    .ou5( s22 )
  );
  \5auf8  \5auf8_i17 (
    .in( s23 ),
    .ou5( s24 )
  );
  conv5to8 conv5to8_i18 (
    .in( s33 ),
    .\10bdd ( s9 )
  );
  conv5to8 conv5to8_i19 (
    .in( s34 ),
    .\10bdd ( s28 )
  );
  shift1 shift1_i20 (
    .in( s1 ),
    .out( s6 )
  );
  shift2 shift2_i21 (
    .in( s3 ),
    .out( s7 )
  );
  shift3 shift3_i22 (
    .in( s5 ),
    .out( s8 )
  );
  shift1 shift1_i23 (
    .in( s20 ),
    .out( s25 )
  );
  shift2 shift2_i24 (
    .in( s22 ),
    .out( s26 )
  );
  shift3 shift3_i25 (
    .in( s24 ),
    .out( s27 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i26 (
    .inTC( s6 ),
    .inBSD( s9 ),
    .bsdOut( s10 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i27 (
    .inTC( s25 ),
    .inBSD( s28 ),
    .bsdOut( s29 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i28 (
    .inTC( s7 ),
    .inBSD( s10 ),
    .bsdOut( s11 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i29 (
    .inTC( s26 ),
    .inBSD( s29 ),
    .bsdOut( s30 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i30 (
    .inTC( s8 ),
    .inBSD( s11 ),
    .bsdOut( s12 ),
    .c( s13 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i31 (
    .inTC( s27 ),
    .inBSD( s30 ),
    .bsdOut( s31 ),
    .c( s32 )
  );
  assign s14[15:0] = s12;
  assign s14[17:16] = s13;
  assign s16[15:0] = s31;
  assign s16[17:16] = s32;
  \18auf24  \18auf24_i32 (
    .in( s14 ),
    .ou5( s15 )
  );
  shift4 shift4_i33 (
    .in( s16 ),
    .out( s17 )
  );
  \13BitBSD  \13BitBSD_i34 (
    .inA( s17 ),
    .inB( s15 ),
    .out( s18 )
  );
  assign s59[3:0] = s18[27:24];
  assign s59[7:4] = 4'b101;
  assign s56 = s18[7:0];
  assign s57 = s18[15:8];
  assign s58 = s18[23:16];
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i35 (
    .sel( s54 ),
    .in_0( s56 ),
    .in_1( s57 ),
    .in_2( s58 ),
    .in_3( s59 ),
    .out( uo_out )
  );
endmodule
