/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Demux3
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    input [2:0] sel,
    input in
);
    assign out_0 = (sel == 3'h0)? in : Default;
    assign out_1 = (sel == 3'h1)? in : Default;
    assign out_2 = (sel == 3'h2)? in : Default;
    assign out_3 = (sel == 3'h3)? in : Default;
    assign out_4 = (sel == 3'h4)? in : Default;
    assign out_5 = (sel == 3'h5)? in : Default;
    assign out_6 = (sel == 3'h6)? in : Default;
    assign out_7 = (sel == 3'h7)? in : Default;
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module \5auf8  (
  input [4:0] in,
  output [7:0] ou5
);
  assign ou5[4:0] = in;
  assign ou5[7:5] = 3'b0;
endmodule

module conv5to8 (
  input [4:0] in,
  output [15:0] \10bdd 
);
  assign \10bdd [0] = in[0];
  assign \10bdd [1] = 1'b1;
  assign \10bdd [2] = in[1];
  assign \10bdd [3] = 1'b1;
  assign \10bdd [4] = in[2];
  assign \10bdd [5] = 1'b1;
  assign \10bdd [6] = in[3];
  assign \10bdd [7] = 1'b1;
  assign \10bdd [8] = in[4];
  assign \10bdd [9] = 1'b1;
  assign \10bdd [10] = 1'b0;
  assign \10bdd [11] = 1'b1;
  assign \10bdd [12] = 1'b0;
  assign \10bdd [13] = 1'b1;
  assign \10bdd [14] = 1'b0;
  assign \10bdd [15] = 1'b1;
endmodule

module shift1 (
  input [7:0] in,
  output [7:0] out
);
  assign out[0] = 1'b0;
  assign out[1] = in[0];
  assign out[2] = in[1];
  assign out[3] = in[2];
  assign out[4] = in[3];
  assign out[5] = in[4];
  assign out[6] = in[5];
  assign out[7] = in[6];
endmodule

module shift2 (
  input [7:0] in,
  output [7:0] out
);
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  assign out[2] = in[0];
  assign out[3] = in[1];
  assign out[4] = in[2];
  assign out[5] = in[3];
  assign out[6] = in[4];
  assign out[7] = in[5];
endmodule

module shift3 (
  input [7:0] in,
  output [7:0] out
);
  wire s0;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  assign out[2] = 1'b0;
  assign out[3] = in[0];
  assign out[4] = in[1];
  assign out[5] = in[2];
  assign out[6] = in[3];
  assign out[7] = in[4];
  assign s0 = in[5];
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module \8bit_BSD_TC_Adder  (
  input [7:0] inTC,
  input [15:0] inBSD,
  output [15:0] bsdOut,
  output [1:0] c
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  assign s17 = inTC[0];
  assign s12 = inTC[1];
  assign s7 = inTC[2];
  assign s2 = inTC[3];
  assign s20 = inTC[4];
  assign s21 = inTC[5];
  assign s22 = inTC[6];
  assign s23 = inTC[7];
  assign s15 = inBSD[0];
  assign s16 = inBSD[1];
  assign s10 = inBSD[2];
  assign s11 = inBSD[3];
  assign s5 = inBSD[4];
  assign s6 = inBSD[5];
  assign s0 = inBSD[6];
  assign s1 = inBSD[7];
  assign s24 = inBSD[8];
  assign s25 = inBSD[9];
  assign s26 = inBSD[10];
  assign s27 = inBSD[11];
  assign s28 = inBSD[12];
  assign s29 = inBSD[13];
  assign s30 = inBSD[14];
  assign s31 = inBSD[15];
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i0 (
    .a( s0 ),
    .b( s1 ),
    .c_i( s2 ),
    .s( s3 ),
    .c_o( s4 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i1 (
    .a( s5 ),
    .b( s6 ),
    .c_i( s7 ),
    .s( s8 ),
    .c_o( s9 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i2 (
    .a( s10 ),
    .b( s11 ),
    .c_i( s12 ),
    .s( s13 ),
    .c_o( s14 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i3 (
    .a( s15 ),
    .b( s16 ),
    .c_i( s17 ),
    .s( s18 ),
    .c_o( s19 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i4 (
    .a( s26 ),
    .b( s27 ),
    .c_i( s21 ),
    .s( s34 ),
    .c_o( s35 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i5 (
    .a( s24 ),
    .b( s25 ),
    .c_i( s20 ),
    .s( s32 ),
    .c_o( s33 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i6 (
    .a( s30 ),
    .b( s31 ),
    .c_i( s23 ),
    .s( s38 ),
    .c_o( s39 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i7 (
    .a( s28 ),
    .b( s29 ),
    .c_i( s22 ),
    .s( s36 ),
    .c_o( s37 )
  );
  assign bsdOut[0] = 1'b0;
  assign bsdOut[1] = s18;
  assign bsdOut[2] = s19;
  assign bsdOut[3] = s13;
  assign bsdOut[4] = s14;
  assign bsdOut[5] = s8;
  assign bsdOut[6] = s9;
  assign bsdOut[7] = s3;
  assign bsdOut[8] = s4;
  assign bsdOut[9] = s32;
  assign bsdOut[10] = s33;
  assign bsdOut[11] = s34;
  assign bsdOut[12] = s35;
  assign bsdOut[13] = s36;
  assign bsdOut[14] = s37;
  assign bsdOut[15] = s38;
  assign c[0] = s39;
  assign c[1] = 1'b1;
endmodule

module \18auf24  (
  input [17:0] in,
  output [25:0] ou5
);
  assign ou5[17:0] = in;
  assign ou5[18] = 1'b0;
  assign ou5[19] = 1'b1;
  assign ou5[20] = 1'b0;
  assign ou5[21] = 1'b1;
  assign ou5[22] = 1'b0;
  assign ou5[23] = 1'b1;
  assign ou5[24] = 1'b0;
  assign ou5[25] = 1'b1;
endmodule

module shift4 (
  input [17:0] in,
  output [25:0] out
);
  assign out[0] = 1'b1;
  assign out[1] = 1'b0;
  assign out[2] = 1'b1;
  assign out[3] = 1'b0;
  assign out[4] = 1'b1;
  assign out[5] = 1'b0;
  assign out[6] = 1'b1;
  assign out[7] = 1'b0;
  assign out[8] = in[0];
  assign out[9] = in[1];
  assign out[10] = in[2];
  assign out[11] = in[3];
  assign out[12] = in[4];
  assign out[13] = in[5];
  assign out[14] = in[6];
  assign out[15] = in[7];
  assign out[16] = in[8];
  assign out[17] = in[9];
  assign out[18] = in[10];
  assign out[19] = in[11];
  assign out[20] = in[12];
  assign out[21] = in[13];
  assign out[22] = in[14];
  assign out[23] = in[15];
  assign out[24] = in[16];
  assign out[25] = in[17];
endmodule

module \13BitBSD  (
  input [25:0] inA,
  input [25:0] inB,
  output [27:0] out
);
  wire \1 ;
  wire \1b ;
  wire \2 ;
  wire s0;
  wire s1;
  wire \2b ;
  wire s2;
  wire s3;
  wire \3 ;
  wire \3b ;
  wire \4 ;
  wire s4;
  wire s5;
  wire \4b ;
  wire s6;
  wire s7;
  wire \5 ;
  wire \5b ;
  wire \6 ;
  wire s8;
  wire s9;
  wire \6b ;
  wire s10;
  wire s11;
  wire \7 ;
  wire \7b ;
  wire \8 ;
  wire s12;
  wire s13;
  wire \8b ;
  wire s14;
  wire s15;
  wire \9 ;
  wire \9b ;
  wire \10 ;
  wire s16;
  wire s17;
  wire \10b ;
  wire s18;
  wire s19;
  wire \11 ;
  wire \11b ;
  wire \12 ;
  wire s20;
  wire s21;
  wire \12b ;
  wire s22;
  wire s23;
  wire \13 ;
  wire \13b ;
  wire \14 ;
  wire s24;
  wire s25;
  wire \14b ;
  wire s26;
  wire s27;
  wire \15 ;
  wire \15b ;
  wire \16 ;
  wire s28;
  wire s29;
  wire \16b ;
  wire s30;
  wire s31;
  wire [15:0] s32;
  wire [15:0] s33;
  wire [15:0] s34;
  wire \1c ;
  wire \1bc ;
  wire \2c ;
  wire s35;
  wire s36;
  wire \2bc ;
  wire s37;
  wire s38;
  wire \3c ;
  wire \3bc ;
  wire \4c ;
  wire s39;
  wire s40;
  wire \4bc ;
  wire s41;
  wire s42;
  wire \5c ;
  wire \5bc ;
  wire \6c ;
  wire s43;
  wire s44;
  wire \6bc ;
  wire s45;
  wire s46;
  wire \7c ;
  wire \7bc ;
  wire \8c ;
  wire s47;
  wire s48;
  wire \8bc ;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire [11:0] s54;
  wire [9:0] s55;
  wire \9c ;
  wire \10c ;
  wire [9:0] s56;
  wire \9bc ;
  wire \10bc ;
  wire s57;
  assign s33 = inA[15:0];
  assign s55 = inA[25:16];
  assign s34 = inB[15:0];
  assign s56 = inB[25:16];
  assign \1  = s33[0];
  assign \2  = s33[1];
  assign \3  = s33[2];
  assign \4  = s33[3];
  assign \5  = s33[4];
  assign \6  = s33[5];
  assign \7  = s33[6];
  assign \8  = s33[7];
  assign \9  = s33[8];
  assign \10  = s33[9];
  assign \11  = s33[10];
  assign \12  = s33[11];
  assign \13  = s33[12];
  assign \14  = s33[13];
  assign \15  = s33[14];
  assign \16  = s33[15];
  assign \1b  = s34[0];
  assign \2b  = s34[1];
  assign \3b  = s34[2];
  assign \4b  = s34[3];
  assign \5b  = s34[4];
  assign \6b  = s34[5];
  assign \7b  = s34[6];
  assign \8b  = s34[7];
  assign \9b  = s34[8];
  assign \10b  = s34[9];
  assign \11b  = s34[10];
  assign \12b  = s34[11];
  assign \13b  = s34[12];
  assign \14b  = s34[13];
  assign \15b  = s34[14];
  assign \16b  = s34[15];
  assign \1c  = s55[0];
  assign \2c  = s55[1];
  assign \3c  = s55[2];
  assign \4c  = s55[3];
  assign \5c  = s55[4];
  assign \6c  = s55[5];
  assign \7c  = s55[6];
  assign \8c  = s55[7];
  assign \9c  = s55[8];
  assign \10c  = s55[9];
  assign \1bc  = s56[0];
  assign \2bc  = s56[1];
  assign \3bc  = s56[2];
  assign \4bc  = s56[3];
  assign \5bc  = s56[4];
  assign \6bc  = s56[5];
  assign \7bc  = s56[6];
  assign \8bc  = s56[7];
  assign \9bc  = s56[8];
  assign \10bc  = s56[9];
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i0 (
    .a( \1  ),
    .b( \1b  ),
    .c_i( \2  ),
    .s( s0 ),
    .c_o( s1 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i1 (
    .a( \3  ),
    .b( \3b  ),
    .c_i( \4  ),
    .s( s4 ),
    .c_o( s5 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i2 (
    .a( \5  ),
    .b( \5b  ),
    .c_i( \6  ),
    .s( s8 ),
    .c_o( s9 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i3 (
    .a( \7  ),
    .b( \7b  ),
    .c_i( \8  ),
    .s( s12 ),
    .c_o( s13 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i4 (
    .a( \9  ),
    .b( \9b  ),
    .c_i( \10  ),
    .s( s16 ),
    .c_o( s17 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i5 (
    .a( \11  ),
    .b( \11b  ),
    .c_i( \12  ),
    .s( s20 ),
    .c_o( s21 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i6 (
    .a( \13  ),
    .b( \13b  ),
    .c_i( \14  ),
    .s( s24 ),
    .c_o( s25 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i7 (
    .a( \15  ),
    .b( \15b  ),
    .c_i( \16  ),
    .s( s28 ),
    .c_o( s29 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i8 (
    .a( \1c  ),
    .b( \1bc  ),
    .c_i( \2c  ),
    .s( s35 ),
    .c_o( s36 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i9 (
    .a( \3c  ),
    .b( \3bc  ),
    .c_i( \4c  ),
    .s( s39 ),
    .c_o( s40 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i10 (
    .a( \5c  ),
    .b( \5bc  ),
    .c_i( \6c  ),
    .s( s43 ),
    .c_o( s44 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i11 (
    .a( \7c  ),
    .b( \7bc  ),
    .c_i( \8c  ),
    .s( s47 ),
    .c_o( s48 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i12 (
    .a( \9c  ),
    .b( \9bc  ),
    .c_i( \10c  ),
    .s( s57 ),
    .c_o( s53 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i13 (
    .a( 1'b1 ),
    .b( s0 ),
    .c_i( \2b  ),
    .s( s2 ),
    .c_o( s3 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i14 (
    .a( s1 ),
    .b( s4 ),
    .c_i( \4b  ),
    .s( s6 ),
    .c_o( s7 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i15 (
    .a( s5 ),
    .b( s8 ),
    .c_i( \6b  ),
    .s( s10 ),
    .c_o( s11 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i16 (
    .a( s9 ),
    .b( s12 ),
    .c_i( \8b  ),
    .s( s14 ),
    .c_o( s15 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i17 (
    .a( s13 ),
    .b( s16 ),
    .c_i( \10b  ),
    .s( s18 ),
    .c_o( s19 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i18 (
    .a( s17 ),
    .b( s20 ),
    .c_i( \12b  ),
    .s( s22 ),
    .c_o( s23 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i19 (
    .a( s21 ),
    .b( s24 ),
    .c_i( \14b  ),
    .s( s26 ),
    .c_o( s27 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i20 (
    .a( s25 ),
    .b( s28 ),
    .c_i( \16b  ),
    .s( s30 ),
    .c_o( s31 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i21 (
    .a( s29 ),
    .b( s35 ),
    .c_i( \2bc  ),
    .s( s37 ),
    .c_o( s38 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i22 (
    .a( s36 ),
    .b( s39 ),
    .c_i( \4bc  ),
    .s( s41 ),
    .c_o( s42 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i23 (
    .a( s40 ),
    .b( s43 ),
    .c_i( \6bc  ),
    .s( s45 ),
    .c_o( s46 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i24 (
    .a( s44 ),
    .b( s47 ),
    .c_i( \8bc  ),
    .s( s49 ),
    .c_o( s50 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i25 (
    .a( s48 ),
    .b( s57 ),
    .c_i( \10bc  ),
    .s( s51 ),
    .c_o( s52 )
  );
  assign s32[0] = 1'b0;
  assign s32[1] = s2;
  assign s32[2] = s3;
  assign s32[3] = s6;
  assign s32[4] = s7;
  assign s32[5] = s10;
  assign s32[6] = s11;
  assign s32[7] = s14;
  assign s32[8] = s15;
  assign s32[9] = s18;
  assign s32[10] = s19;
  assign s32[11] = s22;
  assign s32[12] = s23;
  assign s32[13] = s26;
  assign s32[14] = s27;
  assign s32[15] = s30;
  assign s54[0] = s31;
  assign s54[1] = s37;
  assign s54[2] = s38;
  assign s54[3] = s41;
  assign s54[4] = s42;
  assign s54[5] = s45;
  assign s54[6] = s46;
  assign s54[7] = s49;
  assign s54[8] = s50;
  assign s54[9] = s51;
  assign s54[10] = s52;
  assign s54[11] = s53;
  assign out[15:0] = s32;
  assign out[27:16] = s54;
endmodule

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module TinyTapeoutAdderTree (
  input [7:0] ui_in,
  input clk,
  input [7:0] uio_in,
  output [7:0] uo_out
);
  wire [4:0] s0;
  wire [7:0] s1;
  wire [4:0] s2;
  wire [7:0] s3;
  wire [4:0] s4;
  wire [7:0] s5;
  wire [7:0] s6;
  wire [7:0] s7;
  wire [7:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [1:0] s13;
  wire [17:0] s14;
  wire [25:0] s15;
  wire [17:0] s16;
  wire [25:0] s17;
  wire [27:0] s18;
  wire [4:0] s19;
  wire [7:0] s20;
  wire [4:0] s21;
  wire [7:0] s22;
  wire [4:0] s23;
  wire [7:0] s24;
  wire [7:0] s25;
  wire [7:0] s26;
  wire [7:0] s27;
  wire [15:0] s28;
  wire [15:0] s29;
  wire [15:0] s30;
  wire [15:0] s31;
  wire [1:0] s32;
  wire [4:0] s33;
  wire [4:0] s34;
  wire [4:0] s35;
  wire [1:0] unused_c_i23;
  wire [1:0] unused_c_i24;
  wire [1:0] unused_c_i25;
  wire [1:0] unused_c_i26;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire [2:0] s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire [1:0] s53;
  wire [2:0] s54;
  wire [7:0] s55;
  wire [7:0] s56;
  wire [7:0] s57;
  wire [7:0] s58;
  wire write;
  wire s59;
  wire s60;
  assign s35 = ui_in[4:0];
  assign s43 = uio_in[2:0];
  assign s53 = uio_in[4:3];
  assign s54 = uio_in[7:5];
  Demux3 #(
    .Default(0)
  )
  Demux3_i0 (
    .sel( s43 ),
    .in( 1'b1 ),
    .out_0( s44 ),
    .out_1( s45 ),
    .out_2( s46 ),
    .out_3( s47 ),
    .out_4( s48 ),
    .out_5( s49 ),
    .out_6( s50 ),
    .out_7( s51 )
  );
  assign s59 = s54[0];
  assign s60 = s54[1];
  assign write = s54[2];
  assign s52 = (s44 & write);
  assign s36 = (s45 & write);
  assign s37 = (s46 & write);
  assign s38 = (s47 & write);
  assign s39 = (s48 & write);
  assign s40 = (s49 & write);
  assign s41 = (s50 & write);
  assign s42 = (s51 & write);
  // R1
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i1 (
    .D( s35 ),
    .C( clk ),
    .en( s36 ),
    .Q( s0 )
  );
  // R2
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i2 (
    .D( s35 ),
    .C( clk ),
    .en( s37 ),
    .Q( s2 )
  );
  // R3
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i3 (
    .D( s35 ),
    .C( clk ),
    .en( s38 ),
    .Q( s4 )
  );
  // R4
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i4 (
    .D( s35 ),
    .C( clk ),
    .en( s39 ),
    .Q( s34 )
  );
  // R5
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i5 (
    .D( s35 ),
    .C( clk ),
    .en( s40 ),
    .Q( s19 )
  );
  // R6
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i6 (
    .D( s35 ),
    .C( clk ),
    .en( s41 ),
    .Q( s21 )
  );
  // R7
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i7 (
    .D( s35 ),
    .C( clk ),
    .en( s42 ),
    .Q( s23 )
  );
  // R0
  DIG_Register_BUS #(
    .Bits(5)
  )
  DIG_Register_BUS_i8 (
    .D( s35 ),
    .C( clk ),
    .en( s52 ),
    .Q( s33 )
  );
  \5auf8  \5auf8_i9 (
    .in( s0 ),
    .ou5( s1 )
  );
  \5auf8  \5auf8_i10 (
    .in( s2 ),
    .ou5( s3 )
  );
  \5auf8  \5auf8_i11 (
    .in( s4 ),
    .ou5( s5 )
  );
  \5auf8  \5auf8_i12 (
    .in( s19 ),
    .ou5( s20 )
  );
  \5auf8  \5auf8_i13 (
    .in( s21 ),
    .ou5( s22 )
  );
  \5auf8  \5auf8_i14 (
    .in( s23 ),
    .ou5( s24 )
  );
  conv5to8 conv5to8_i15 (
    .in( s33 ),
    .\10bdd ( s9 )
  );
  conv5to8 conv5to8_i16 (
    .in( s34 ),
    .\10bdd ( s28 )
  );
  shift1 shift1_i17 (
    .in( s1 ),
    .out( s6 )
  );
  shift2 shift2_i18 (
    .in( s3 ),
    .out( s7 )
  );
  shift3 shift3_i19 (
    .in( s5 ),
    .out( s8 )
  );
  shift1 shift1_i20 (
    .in( s20 ),
    .out( s25 )
  );
  shift2 shift2_i21 (
    .in( s22 ),
    .out( s26 )
  );
  shift3 shift3_i22 (
    .in( s24 ),
    .out( s27 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i23 (
    .inTC( s6 ),
    .inBSD( s9 ),
    .bsdOut( s10 ),
    .c( unused_c_i23 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i24 (
    .inTC( s25 ),
    .inBSD( s28 ),
    .bsdOut( s29 ),
    .c( unused_c_i24 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i25 (
    .inTC( s7 ),
    .inBSD( s10 ),
    .bsdOut( s11 ),
    .c( unused_c_i25 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i26 (
    .inTC( s26 ),
    .inBSD( s29 ),
    .bsdOut( s30 ),
    .c( unused_c_i26 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i27 (
    .inTC( s8 ),
    .inBSD( s11 ),
    .bsdOut( s12 ),
    .c( s13 )
  );
  \8bit_BSD_TC_Adder  \8bit_BSD_TC_Adder_i28 (
    .inTC( s27 ),
    .inBSD( s30 ),
    .bsdOut( s31 ),
    .c( s32 )
  );
  assign s14[15:0] = s12;
  assign s14[17:16] = s13;
  assign s16[15:0] = s31;
  assign s16[17:16] = s32;
  \18auf24  \18auf24_i29 (
    .in( s14 ),
    .ou5( s15 )
  );
  shift4 shift4_i30 (
    .in( s16 ),
    .out( s17 )
  );
  \13BitBSD  \13BitBSD_i31 (
    .inA( s17 ),
    .inB( s15 ),
    .out( s18 )
  );
  assign s58[3:0] = s18[27:24];
  assign s58[7:4] = 4'b101;
  assign s55 = s18[7:0];
  assign s56 = s18[15:8];
  assign s57 = s18[23:16];
  Mux_4x1_NBits #(
    .Bits(8)
  )
  Mux_4x1_NBits_i32 (
    .sel( s53 ),
    .in_0( s55 ),
    .in_1( s56 ),
    .in_2( s57 ),
    .in_3( s58 ),
    .out( uo_out )
  );
endmodule
